on: push
name: test, build y subida a DockerHub
jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
    steps:
      #configuración de node
      - uses: actions/checkout@v2
      - name: Uso de Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - run: docker build -t containertest .
      - run: docker run containertest


#https://github.com/docker/build-push-action
#https://docs.docker.com/ci-cd/github-actions/
#https://blog.bitsrc.io/https-medium-com-adhasmana-how-to-do-ci-and-cd-of-node-js-application-using-github-actions-860007bebae6
