on: push
name: test, build y subida a DockerHub
jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
    steps:
      #configuración de node
      - uses: actions/checkout@v2
      - name: Uso de Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      #instalación y tests
      - run: npm install
      - run: npm test
      #qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      #buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #se hace el login con los secrets creados
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #build y push
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: albertolejarraga/percepcion-relativa-deportistas:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

#https://github.com/docker/build-push-action
#https://docs.docker.com/ci-cd/github-actions/
#https://blog.bitsrc.io/https-medium-com-adhasmana-how-to-do-ci-and-cd-of-node-js-application-using-github-actions-860007bebae6
