on: push
name: test container
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t containertest .
      - run: docker run containertest


#https://github.com/docker/build-push-action
#https://docs.docker.com/ci-cd/github-actions/
#https://blog.bitsrc.io/https-medium-com-adhasmana-how-to-do-ci-and-cd-of-node-js-application-using-github-actions-860007bebae6
