on: push
name: build y test a partir del contenedor
jobs:
  test-docker-container:
    runs-on: ubuntu-latest
    steps:
      #checkout del repo para poder acceder a él en el fichero
      - uses: actions/checkout@v2
      #se buildea y corre el contenedor generado con ./Dockerfile
      - run: docker build -t containertest .
      - run: docker run containertest
