on: push
name: build y test a partir del dockerfile
jobs:
  test-docker-container:
    runs-on: ubuntu-latest
    steps:
      #checkout del repo para poder acceder a él en el fichero
      - name: Checkout del repo
        uses: actions/checkout@v2
      #se buildea y corre el contenedor generado con ./Dockerfile
      - name: build y deploy
        uses: actions/build-and-deploy
        with:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
