on: push
name: test, build y subida a DockerHub
jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Uso de Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - run: npm install
      - run: npm test
      
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t albertolejarraga/percepcion-relativa-deportistas .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push albertolejarraga/percepcion-relativa-deportistas
